### ISSUE TITLE
Work fine on mobile but showing error on web

### ISSUE THREAD

**Issue by faturachmanyusup** [faturachmanyusup/sudoku#1]

**Comment by Dgiulian** [comment]
Let me take a look at it. Hope I can help

**Comment by faturachmanyusup** [comment]
Sure. Thanks.

**Comment by Dgiulian** [comment]
I've never seen a function in the `Stylesheet.create`. Are you sure that's a valid syntax?

**Comment by faturachmanyusup** [comment]
Definitely not the best practice. I just tried to make it responsive for every screen.
